# Generated by Django 4.2 on 2024-06-14 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='covers')),
                ('genre', models.CharField(choices=[('Dystopia', 'Dystopia'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Spy', 'Spy'), ('Contemporary', 'Contemporary')], default='', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
