# Generated by Django 4.2 on 2024-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url_title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
