# Generated by Django 4.2 on 2024-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url_title',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
