# Generated by Django 4.2 on 2024-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Dystopia', 'Dystopia'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Spy', 'Spy'), ('Contemporary', 'Contemporary'), ('Unclassified', 'Unclassified')], default='', max_length=20),
        ),
    ]
